In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [ ]:
df= pd.read_csv("/content/FuelConsumption.csv")

In [ ]:
df.head (10)

MODELYEAR   MAKE       MODEL VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0       2014  ACURA         ILX      COMPACT         2.0          4   
1       2014  ACURA         ILX      COMPACT         2.4          4   
2       2014  ACURA  ILX HYBRID      COMPACT         1.5          4   
3       2014  ACURA     MDX 4WD  SUV - SMALL         3.5          6   
4       2014  ACURA     RDX AWD  SUV - SMALL         3.5          6   
5       2014  ACURA         RLX     MID-SIZE         3.5          6   
6       2014  ACURA          TL     MID-SIZE         3.5          6   
7       2014  ACURA      TL AWD     MID-SIZE         3.7          6   
8       2014  ACURA      TL AWD     MID-SIZE         3.7          6   
9       2014  ACURA         TSX      COMPACT         2.4          4   

  TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0          AS5        Z                   9.9                  6.7   
1           M6        Z                  11.2                  7.7   
2          AV7        Z                   6.0                  5.8   
3          AS6        Z                  12.7                  9.1   
4          AS6        Z                  12.1                  8.7   
5          AS6        Z                  11.9                  7.7   
6          AS6        Z                  11.8                  8.1   
7          AS6        Z                  12.8                  9.0   
8           M6        Z                  13.4                  9.5   
9          AS5        Z                  10.6                  7.5   

   FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                   8.5                        33           196  
1                   9.6                        29           221  
2                   5.9                        48           136  
3                  11.1                        25           255  
4                  10.6                        27           244  
5                  10.0                        28           230  
6                  10.1                        28           232  
7                  11.1                        25           255  
8                  11.6                        24           267  
9                   9.2                        31           212

In [ ]:
df.shape

(1067, 13)

In [ ]:
x=df[["ENGINESIZE"]].values
y=df["CO2EMISSIONS"].values

In [ ]:
df.isnull().sum()

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

In [ ]:
x

array([[2. ],
       [2.4],
       [1.5],
       ...,
       [3. ],
       [3.2],
       [3.2]])

In [ ]:
y

array([196, 221, 136, ..., 271, 260, 294])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=1)

In [ ]:
reg=LinearRegression()

In [ ]:
reg.fit(x_train, y_train)


LinearRegression()

In [ ]:
reg.predict(x_test)

array([242.88082083, 179.60282889, 203.33207587, 203.33207587,
       306.15881277, 242.88082083, 203.33207587, 195.42232688,
       242.88082083, 219.15157386, 219.15157386, 242.88082083,
       219.15157386, 329.88805975, 223.10644835, 223.10644835,
       187.51257789, 298.24906378, 262.65519331, 219.15157386,
       361.52705572, 223.10644835, 270.56494231, 262.65519331,
       270.56494231, 242.88082083, 171.6930799 , 341.75268324,
       187.51257789, 203.33207587, 242.88082083, 329.88805975,
       262.65519331, 333.84293425, 282.42956579, 333.84293425,
       369.43680471, 183.55770339, 290.33931479, 254.74544432,
       242.88082083, 373.39167921, 203.33207587, 266.61006781,
       270.56494231, 203.33207587, 179.60282889, 179.60282889,
       203.33207587, 258.70031882, 187.51257789, 349.66243223,
       294.29418928, 369.43680471, 203.33207587, 270.56494231,
       223.10644835, 321.97831076, 270.56494231, 187.51257789,
       219.15157386, 231.01619734, 203.33207587, 203.33

In [ ]:
reg.intercept_

124.23458594672331

In [ ]:
reg.coef_

array([39.54874496])

In [ ]:
reg.predict(x_test)

array([242.88082083, 179.60282889, 203.33207587, 203.33207587,
       306.15881277, 242.88082083, 203.33207587, 195.42232688,
       242.88082083, 219.15157386, 219.15157386, 242.88082083,
       219.15157386, 329.88805975, 223.10644835, 223.10644835,
       187.51257789, 298.24906378, 262.65519331, 219.15157386,
       361.52705572, 223.10644835, 270.56494231, 262.65519331,
       270.56494231, 242.88082083, 171.6930799 , 341.75268324,
       187.51257789, 203.33207587, 242.88082083, 329.88805975,
       262.65519331, 333.84293425, 282.42956579, 333.84293425,
       369.43680471, 183.55770339, 290.33931479, 254.74544432,
       242.88082083, 373.39167921, 203.33207587, 266.61006781,
       270.56494231, 203.33207587, 179.60282889, 179.60282889,
       203.33207587, 258.70031882, 187.51257789, 349.66243223,
       294.29418928, 369.43680471, 203.33207587, 270.56494231,
       223.10644835, 321.97831076, 270.56494231, 187.51257789,
       219.15157386, 231.01619734, 203.33207587, 203.33

In [ ]:
reg.score(x_test,y_test)


0.7633265438534859